### ISSUE TITLE
Maximized windows with titlebar have a bad size

### ISSUE THREAD

**Issue by syll-dev** [awesomeWM/awesome#1128]
Output of `awesome --version`:

awesome v3.5.9 (Mighty Ravendark)
 • Build: Mar 12 2016 01:11:40 for x86_64 by gcc version 5.3.0 (builduser@rw)
 • Compiled against Lua 5.3.2 (running with Lua 5.3)
 • D-Bus support: ✔

**How to reproduce the issue:**

Maximize a window with a titlebar from an application that will maximize the window again when restarting (tried with eclipse and claws-mail on archlinux).
Close the application.
Start the application.

I think this is the code used to add titlebar to windows :

```
local titlebars_enabled = true
if titlebars_enabled and (c.type == "normal" or c.type == "dialog") then
    -- Widgets that are aligned to the left
    local left_layout = wibox.layout.fixed.horizontal()
    left_layout:add(awful.titlebar.widget.iconwidget(c))

    -- Widgets that are aligned to the right
    local right_layout = wibox.layout.fixed.horizontal()
    right_layout:add(awful.titlebar.widget.floatingbutton(c))
    right_layout:add(awful.titlebar.widget.maximizedbutton(c))
    right_layout:add(awful.titlebar.widget.stickybutton(c))
    right_layout:add(awful.titlebar.widget.ontopbutton(c))
    right_layout:add(awful.titlebar.widget.closebutton(c))

    -- The title goes in the middle
    local title = awful.titlebar.widget.titlewidget(c)
    title:buttons(awful.util.table.join(
            awful.button({ }, 1, function()
                client.focus = c
                c:raise()
                awful.mouse.client.move(c)
            end),
            awful.button({ }, 3, function()
                client.focus = c
                c:raise()
                awful.mouse.client.resize(c)
            end)
            ))

    -- Now bring it all together
    local layout = wibox.layout.align.horizontal()
    layout:set_left(left_layout)
    layout:set_right(right_layout)
    layout:set_middle(title)

    awful.titlebar(c):set_widget(layout)
end
```

**Actual result:**

The window is too large and its bottom is out of the screen. The window probably has been sized, then the titlebar added and window content moved to the bottom.

**Expected result:**

The maximized window + titlebar should not be larger than the screen (minus "task bar").

**Comment by psychon** [comment]
> Maximize a window with a titlebar from an application that will maximize the window again when restarting (tried with eclipse and claws-mail on archlinux).
> Close the application.
> Start the application.

Since I have neither of those: Could you get `xprop` output for the application after it was restarted? Does `_NET_WM_STATE` include `_NET_WM_STATE_MAXIMIZED_VERTICALLY` and `_NET_WM_STATE_MAXIMIZED_HORIZONTALLY`? (You can also check if these entries are present before the restart...)
If they are not present, then only the geometry is restored, but not actually the maximized state.
If they are present... uhm. Let's take a look at `awful.ewmh`... Ok. Could you test if before e54387904b16e3087cb989e862d9c98196a6d7b7 (so in commit e54387904b16e3087cb989e862d9c98196a6d7b7^) this bug was also present? If not, could you do a `git bisect` to see where it was introduced?

**Comment by blueyed** [comment]
First test if it actually happens on master.

**Comment by psychon** [comment]
Ups. Sorry, I missed that this issue is against v3.5.9. Just ignore my comment above then.

**Comment by syll-dev** [comment]
Before restart (window state changed to normal then changed back to maximized (with keyboard)) :
```
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_MAXIMIZED_HORZ

```

After restart (application restarted without changing anything alse) :
```
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_MAXIMIZED_HORZ
```

The "maximized" icon is colored (active).

Is it something that has been corrected since 3.5.9 ?

Other applications (leafpad for example) that start non-maximized are placed a little too far towards the bottom of the screen : the top of the window is not at the top of the screen (maybe in the middle, ok) and the bottom of the window is under the bottom of the screen (by about the height of the titlebar).

**Comment by Elv13** [comment]
It has been fixed. I tried to reproduce and it behaves as expected (as of git-master)

**Comment by mgh5225** [comment]
I have the same issue here and I think it is not fixed.
Output of `awesome --version`:

```
awesome v4.3-1585-g1239cdf4b (Too long)
 • Compiled against Lua 5.4.4 (running with 0.9.2)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua
 • Transparency enabled: yes
 • Custom search paths: no
```

Also, the rules section of my rc.lua is:

```
ruled.client.connect_signal("request::rules", function()
    -- All clients will match this rule.
    ruled.client.append_rule {
        id         = "global",
        rule       = {},
        properties = {
            focus     = awful.client.focus.filter,
            raise     = true,
            screen    = awful.screen.preferred,
            placement = awful.placement.no_overlap + awful.placement.no_offscreen
        }
    }

    -- Floating clients.
    ruled.client.append_rule {
        id         = "floating",
        rule_any   = {
            instance = { "copyq", "pinentry" },
            class    = {
                "Arandr", "Blueman-manager", "Gpick", "Kruler", "Sxiv",
                "Tor Browser", "Wpa_gui", "veromix", "xtightvncviewer"
            },
            -- Note that the name property shown in xprop might be set slightly after creation of the client
            -- and the name shown there might not match defined rules here.
            name     = {
                "Event Tester", -- xev.
            },
            role     = {
                "AlarmWindow", -- Thunderbird's calendar.
                "ConfigManager", -- Thunderbird's about:config.
                "pop-up", -- e.g. Google Chrome's (detached) Developer Tools.
            }
        },
        properties = { floating = true }
    }

    -- Add titlebars to normal clients and dialogs
    ruled.client.append_rule {
        id         = "titlebars",
        rule_any   = { type = { "normal", "dialog" } },
        properties = { titlebars_enabled = true }
    }
end)
```
