### ISSUE TITLE
Run-/Lua- Prompt not working with special xkb-layout (Neo/Bone)

### ISSUE THREAD

**Issue by the193rd** [awesomeWM/awesome#157]
Awesome Version 3.5.6-1 (from the arch-community repo)

I am using an alternative keyboard layout (using `setxkbmap de neo`, after I started awesome wm), which utilizes CapsLock and AltGr to get more than 2 layers. (example: `a`, `A`, `{`, `<DOWN>`, `α` and `∀` are all located on the qwerty-key d and caps+d gives you `{`)

The Run- and the Lua-prompt are ignoring those additional modifiers (Caps, AltGr). The result is just the letter from layer 1.

**Comment by blueyed** [comment]
Confirmed.
After `setxkbmap de neo`, `mod4+k` (on the qwertz layout) will start the run prompt, and the Neo modifiers (e.g. AltGr/Mod4, `#`/Mod3) don't make a difference.

(For reference: http://www.neo-layout.org/)

**Comment by blueyed** [comment]
Printing the keycode and modifiers, which `run` receives (in lib/awful/prompt.lua.in), it looks like this for `AltGr-d`: 

> key: a
mod:Mod2
mod:Mod5

I could imagine that the keygrabber is not properly / fully resolving the keypresses, and that https://awesome.naquadah.org/bugs/index.php?do=details&task_id=1104 ("support XLookupString or XKeysymToKeycode") might be relevant / required here.

**Comment by psychon** [comment]
Should be fixed with #227. Can anyone test? (I can't right now)

**Comment by blueyed** [comment]
Seems to work: but I've needed to restart awesome to pick up the new layout for the hotkeys, i.e. the mapping works as expected in the run-prompt, but you need to restart awesome to trigger the run-prompt through `super-k` (which is `super-r` on the neo layout).
Is this expected?  Or should the layout switching be handled by awesome already, to make `super-k` trigger the run prompt?

**Comment by psychon** [comment]
Just to be sure, you ran `setxkbmap de neo` and awesome was still using the old keyboard layout? Hm. I guess we don't update the right thing in `event_handle_xkb_notify`... or we aren't requesting all the events we need in `xkb_init`... or something.

**Comment by psychon** [comment]
Comparing our code with https://github.com/i3/i3/commit/3f5a0f0024 I spot calls like `ungrab_all_keys(conn); grab_all_keys(conn, false);`. I guess we need to re-grab keys like this, too. That would also explain the behavior you see.

**Comment by blueyed** [comment]
@psychon 
> you ran `setxkbmap de neo` and awesome was still using the old keyboard layout

For the hotkeys, yes.  The run prompt itself used the new layout.

Do you feel like coming up with a PR to fix this fully?

**Comment by psychon** [comment]
Will (hopefully remember to) investigate. However, technically this bug can be closed since the issue that is reported was fixed and we are now looking at a different issue. ;-)

**Comment by psychon** [comment]
No time to test right now, but here's a completely untested patch:
```diff
diff --git a/xkb.c b/xkb.c
index 82db23b..e4d9c1a 100644
--- a/xkb.c
+++ b/xkb.c
@@ -25,6 +25,8 @@
 
 #include "xkb.h"
 #include "globalconf.h"
+#include "xwindow.h"
+#include "objects/client.h"
 #include <xcb/xkb.h>
 #include <xkbcommon/xkbcommon.h>
 #include <xkbcommon/xkbcommon-x11.h>
@@ -183,6 +185,11 @@ xkb_reload_keymap(void)
 {
     xkb_state_unref(globalconf.xkb_state);
     xkb_fill_state();
+
+    /* Re-grab all keys */
+    xwindow_grabkeys(globalconf.screen->root, &globalconf.keys);
+    foreach(c, globalconf.clients)
+        xwindow_grabkeys((*c)->frame_window, &(*c)->keys);
 }
 
 /** The xkb notify event handler.
```
(`frame_window` becomes `window` when #496 is fixed)

**Comment by svexican** [comment]
psychon's patch works partially. It fixes another problem.
(I use colemak btw)

If the layout is set before awesome starts (eg. via xorg.conf), awesome behaves properly (which didn't before this patch)

However, if the layout is changed with ``setxkbmap`` to something else, awesome keybinds will remain with the old layout.

Should I open another issue? This is drifting away from the original...

**Comment by psychon** [comment]
Ok, I finally looked into this again. Well, apparently we still do not support XKB properly. I guess we have to get rid of `globalconf.keysyms` and replace each of its uses with the corresponding libxkbcommon-based alternative. This affects `root.fake_input`, passive grabs (=global and per-client keybinedings). I guess this means that only the keygrabber actually supports XKB-stuff.

**Comment by psychon** [comment]
The remaining problem is mostly fixed with https://github.com/psychon/awesome/commit/5ce2cbd086fa6fa90d4f1f9a8ef65ac76246e9ba, but that breaks other stuff (see the changes to the default config in the same commit). Fixing this properly requires switching to libxkbcommon properly (as I said in the last commit, we still use the "old", non-XKB code in some places).

**Comment by psychon** [comment]
This should be fixed with a98fc92b81f52a61ce94774bfc9271778b86f189 in the master branch. Please reopen if not.

**Comment by zommerfelds** [comment]
I'm still having this issue with 3.5.9.

**Comment by Elv13** [comment]
@zommerfelds Please try with the master branch (to be Awesome 3.6). Non trivial bug fixes are not backported into 3.5.* anymore. There was fixed for keyboard layout in 3.5.8, but not this one.

**Comment by zommerfelds** [comment]
I confirm that this partially fixed on a more recent version of Awesome (I tested it with [awesome-git](https://aur.archlinux.org/packages/awesome-git/) from the Arch Linux User Repository, not sure if that is the latest master branch).

The layer 3 modifiers (caps lock) were working, however, layer 4 (Alt Gr) was not working for me. Layer 4 contains keys such as the arrow keys or the enter key. This is not a big problem for me, but I thought I should note that here.
