### ISSUE TITLE
Other clients cannot auto resize and adjust when a client maximized under layout corner & tile

### ISSUE THREAD

**Issue by Bekcpear** [awesomeWM/awesome#1662]
Sorry to bother. 
This problem is a little hard to say vary clearly, and also cannot search explicitly. I have searched but no related solutions.

**Output of `awesome --version`:**

```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.0
```

**How to reproduce the issue:**

0. switch to a new tag without client
1. switch layout to tile or corner
2. open at least 3 clients (and have at least one client with transparency)
3. focus the transparent client
4. press `mod4 + m` (the default key binding used to maximize a client)

(*Note: transparent client is not the requirement to reproduce the issue, it's just for convenient observation, you can also keep other clients on top to observe.*)

**Actual result:**

The focused client can be maximum, but the other two clients cannot auto resize and adjust their layout. It cannot return to normal until I press `mod4 + Tab`(the default key binding used to switch between two clients).

**Expected result:**

When I maximize one client, the others can auto resize and adjust their layout as expected.

**Comment by Veratil** [comment]
Hi @Bekcpear, can you try with v4.1? I cannot reproduce the issue there.

**Comment by Bekcpear** [comment]
Hi @Veratil,  thanks for your reply.

I use Gentoo and there is no v4.1 awesome in portage repository. I will try it later as soon as the repository updated.

**Comment by Bekcpear** [comment]
I have updated my awesomewm to version 4.1, the problem is still. Paste a pic here:

![](https://p.ume.ink/i/f8/bd81752bc7bb2c9272959eb84f1ac8bb141eae.png)

I have no idea how to debug it. Could it be an environmental problem?

**Comment by bew** [comment]
I have thus behavior too, but iirc it's wanted

**Comment by Elv13** [comment]
This is not a bug, it is the way it's done. The other tiled client wont move as it is expected that a client covers them, thus they should be invisible. You have an issue because your clients are semi-transparent.

**Comment by Bekcpear** [comment]
@Elv13  Thank you for your explanation, but the floating icon has not changed when the client maximizes.

**Comment by Elv13** [comment]
Fullscreen and maximized clients are not floating. Those are different properties.

**Comment by psychon** [comment]
> This is not a bug, it is the way it's done. 

```
$ grep maximized lib/awful/layout/init.lua
capi.client.connect_signal("property::maximized_horizontal", arrange_prop_nf)
capi.client.connect_signal("property::maximized_vertical", arrange_prop_nf)
```
This bug was introduced in 3b1599bd990cc6f9d73f232faca580ce79b7cf53. Before that, there was no `maximized` state, only `maximized_vertical` and `maximized_horizontal`. Thus, it was enough for the layout code to connect to the signals for those two properties. The above commit made the `maximized` state a "real" client property, but forgot to check all places that need to connect to the signal for this new property.

The fix for this bug is as simple as the following patch, but I guess someone (meh, meh?) should check all the other places that connect to `property::maximized_horizontal` and `property::maximized_vertical` for if they also need `property::maximized`.
```diff
diff --git a/lib/awful/layout/init.lua b/lib/awful/layout/init.lua
index b8100bb..0518b78 100644
--- a/lib/awful/layout/init.lua
+++ b/lib/awful/layout/init.lua
@@ -240,6 +240,7 @@ capi.client.connect_signal("property::sticky", arrange_prop_nf)
 capi.client.connect_signal("property::fullscreen", arrange_prop_nf)
 capi.client.connect_signal("property::maximized_horizontal", arrange_prop_nf)
 capi.client.connect_signal("property::maximized_vertical", arrange_prop_nf)
+capi.client.connect_signal("property::maximized", arrange_prop_nf)
 capi.client.connect_signal("property::border_width", arrange_prop_nf)
 capi.client.connect_signal("property::hidden", arrange_prop_nf)
 capi.client.connect_signal("property::floating", arrange_prop)
```

**Comment by psychon** [comment]
> Fullscreen and maximized clients are not floating. Those are different properties.

(Kind of) wrong:
```Lua
function client.object.get_floating(c)
    c = c or capi.client.focus
    if c then
        local value = client.property.get(c, "floating")
        if value ~= nil then
            return value
        end
        if c.type ~= "normal"
            or c.fullscreen
            or c.maximized_vertical
            or c.maximized_horizontal
            or c.maximized
            or client.object.is_fixed(c) then
            return true
        end
        return false
    end
end
```
Patch could be the following, but perhaps it would be nicer to somehow figure out how we can make `property::floating` be emitted if the floating state changed due to the client becoming maximized....
```diff
diff --git a/lib/awful/titlebar.lua b/lib/awful/titlebar.lua
index 5f3fd75..cd44c1c 100644
--- a/lib/awful/titlebar.lua
+++ b/lib/awful/titlebar.lua
@@ -675,6 +675,10 @@ end
 function titlebar.widget.floatingbutton(c)
     local widget = titlebar.widget.button(c, "floating", aclient.object.get_floating, aclient.floating.toggle)
     c:connect_signal("property::floating", widget.update)
+    c:connect_signal("property::fullscreen", widget.update)
+    c:connect_signal("property::maximized_vertical", widget.update)
+    c:connect_signal("property::maximized_horizontal", widget.update)
+    c:connect_signal("property::maximized", widget.update)
     return widget
 end
 
```

**Comment by Bekcpear** [comment]
> `+    c:connect_signal("property::fullscreen", widget.update)`
> `+    c:connect_signal("property::maximized_vertical", widget.update)`
> `+    c:connect_signal("property::maximized_horizontal", widget.update)`
> `+    c:connect_signal("property::maximized", widget.update)`

This patch works, thanks very much @psychon 


> `+capi.client.connect_signal("property::maximized", arrange_prop_nf)`

This patch has no effect here.

**Comment by psychon** [comment]
#1776 should fix this by ensuring that the `property::floating` signal is always emitted, also when it changes implicitly because a client become maximized. It would be nice if you could test that patch (it only touches `/usr/share/awesome/lib/awful/client.lua` and so might be (relatively) easy to try out by just applying the patch to that file (remember to have a backup of the old file)).

**Comment by Bekcpear** [comment]
Yes, Great! It has been fixed. I really appreciate your help in resolving the problem. @psychon 

And I will close this issue.

**Comment by psychon** [comment]
Thanks for testing and great that this actually fixes all the issues. I never looked closely at why some part of the above patches didn't fix some issues for you.

Reopening until #1776 is merged (since this issue is not yet fixed in the master branch, there is just a fix available).
