### ISSUE TITLE
Discussion: Request: Add awesome.conf_path

### ISSUE THREAD

**Issue by Sorky** [awesomeWM/awesome#2525]
Remove the need for gears.filesystem.get_configuration_dir() or doing awesome.conffile:match(".*/")

Much like theme_path and icon_path?

**Comment by psychon** [comment]
Uhm...
```
$ awesome-client 'return awesome.conffile'
   string "/home/psychon/.config/awesome/rc.lua"
```

**Comment by psychon** [comment]
Sorry, but I am still confused. Why does this have to be in C? What can C do better than Lua here? String manipulations is one of the prime examples that people get wrong in C all the time. Also, the C code would just do the equivalent of `awesome.conffile:match(".*/") or "./"` anyway. What should it do different?

Sorry for failing to see the point here.

**Comment by Sorky** [comment]
I'm (possibly pointlessly) just thinking of efficiency...

I've seen a number of instances (and have done several myself in multiple files) of gears.filesystem.get_configuration_dir() or awesome.conffile:match(".*/") 

It seems a waste of CPU to re-do calculations multiple times when the config path is dare I say constant - on seeing awesome.theme_path and awesome.icon_path I figure there's a case for  awesome.conf_path

I only mention C because I was guessing all awesome.xxx_path were in C rather than lua

**Comment by Sorky** [comment]
Interesting

Forgive my inability to express myself properly - CPU usage is not an "issue", just a consideration and I understand there are bigger fish to fry

My mind is simply on removing lua code that I see repeating and having things where I imagine they make sense

Following the "constants" and "globals" theme - Is there progress on the globals in rc.lua? for instance, terminal is one I see re-done in various places

**Comment by actionless** [comment]
again, what is the problem with using `gears.filesystem.get_configuration_dir() `?

**Comment by Sorky** [comment]
gears.filesystem.get_configuration_dir() re-generates what is essentially a constant whenever called

If you need it in multiple modules you must require("gears") and then call it to re-calculate what essentially is an already known constant that ideally can be accessed immediately

Case in point...

  awesome.icon_path exists
  awesome.themes_path exists

  why not awesome.config_path?

I believe I have determined the changes required...

ADD TO config.h
	#define AWESOME_CONF_DIR  "@AWESOME_SYSCONFDIR@"

ADD TO luaa.c
    if(A_STREQ(buf, "conf_path"))
    {
        lua_pushliteral(L, AWESOME_CONF_DIR);
        return 1;
    }


__OR POSSIBLY SIMPLER ???__


ADD TO luaa.c
    if(A_STREQ(buf, "conf_path"))
    {
        lua_pushstring(L, confpath);
        return 1;
    }

However I'm not familiar enough to be sure but hopefully that illustrates that it should be possible to access the path without a "match" or a lua module

**Comment by psychon** [comment]
> awesome.icon_path exists
> awesome.themes_path exists
> 
> why not awesome.config_path?

The first two are harcoded paths during configure. They just provide the paths that were configured to themes and icons.

> #define AWESOME_CONF_DIR "@AWESOME_SYSCONFDIR@"

Uhm, this would always give you the equivalent of `/etc/xdg/awesome`. I do not think that's the value that you actually want here. If the config was loaded from `~/.config/xdg/awesome`, then this is the path that should be given to Lua, I think.

>  lua_pushstring(L, confpath);

This would give you something like: "Undefined variable `confpath`"
Also, the only variable that is called `confpath` somewhere in that file is copied to the global `conffile` in `luaA_loadrc` and made available to Lua as `awesome.conffile`. The name of the directory does not yet exist in any variable in there and would need to be computed separately.

**Comment by Sorky** [comment]
Job done...

[luaa.c,txt](https://github.com/awesomeWM/awesome/files/2730965/luaa.c.txt)
[luaa.c.orig.txt](https://github.com/awesomeWM/awesome/files/2730966/luaa.c.orig.txt)

Also successfully tested with awesome reloading
Also successfully tested with awesome -c any_path_and_name

**Comment by psychon** [comment]
With your version of `luaa.c`:
```
$ DISPLAY=:1 ./awesome -c awesomerc.lua
2019-01-07 08:00:56 E: awesome: signal_fatal:457: signal 11, dumping backtrace
./awesome(backtrace_get+0x47) [0x5651c7afce01]
./awesome(+0x12f7f) [0x5651c7ae8f7f]
/lib/x86_64-linux-gnu/libc.so.6(+0x378e0) [0x7ff6c38c58e0]
./awesome(+0x1c942) [0x5651c7af2942]
./awesome(luaA_find_config+0x1d) [0x5651c7af3cd8]
./awesome(luaA_parserc+0xd) [0x5651c7af3e93]
./awesome(main+0xf6b) [0x5651c7aea227]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7ff6c38b209b]
```

**Comment by Sorky** [comment]
Nice find - my tests were with /home/user/.config/awesome/xyz.lua & /home/user/xyz.lua - Never tried it without a path - Problem notes and will for correct it

**Comment by Sorky** [comment]
I just tried awesome -c xyz.lua with the original build and got...

cannot open xyz.lua: No such file or directory - Seems to me that -c must have a full path...

Will I assume the test is invalid and just ensure it doesn't crash (catch the NULL)
or try and improve it?

**Comment by psychon** [comment]
Well, is there an `awesomerc.lua` in the path that you ran this from?
I tested this in my git build of awesome and it works fine (of course only after I started `Xephyr :1` in another terminal): `make && cd build && DISPLAY=:1 ./awesome -c awesomerc.lua`

**Comment by Sorky** [comment]
Finally installed Xephyr - Note for other ubuntu apt users : Be aware that two symlinks may be needed...
    
    /usr/local/etc/xdg/awesome -> /etc/xdg/awesome
    /usr/local/share/awesome -> /usr/share/awesome

Fixed the NULL case ;-)

[luaa.c.txt](https://github.com/awesomeWM/awesome/files/2736596/luaa.c.txt)

**Comment by actionless** [comment]
i still don't see a point of that, but just a sidenote -- instead of submitting full file, submit only patch between the master and your work

**Comment by Sorky** [comment]
My reasoning,,,
    Saves repeated execution of awesome.conffile:match(".*/") with multiple use of gears.filesystem.get_configuration_dir()
    Saves using require("gears.filesystem")
    Bonus = Will allow deprecation of get_configuration_dir

[diff.txt](https://github.com/awesomeWM/awesome/files/2737074/diff.txt)

**Comment by Sorky** [comment]
While I agree in principle there are many reasons I raised the discussion / request...
```
    What you suggest is not standard
    Such customization may cause an issue 
    It isn't documented
    Still needs a "require"
    Trying to make it easier for new users
```
In my current personal config I actually do what you suggest with beautiful as I "require" it quite often...
```
-- User defined constants
    me._modkey	= "Mod4"
    me._altkey		= "Mod1"
    me._editor		= "xfwrite"
    me._browser	= "firefox"
    me._terminal	= "xterm"

    me.config_path	= awesome.conffile:match(".*/")
```
Anyway, the suggestion is out there and the change is coded for consideration

**Comment by Veratil** [comment]
* If we updated the `gears.filesystem` API then it would be standard
* We don't remove API unless it's deprecated and given a version for people to fix their config
* Again, if we updated the API then it would be documented. This isn't a valid point to me.
* A minor inconvenience to need a "require"
* I will agree this would be easier to type, but you'd still probably have to look at the API for it

I'm not saying your idea is bad, I'm just saying I don't think it's a problem.

**Comment by Sorky** [comment]
If you're suggesting adding `filesystem.conf_path = awesome.conffile:match(".*/") or "./"` to filesystem.lua then yes that would become standard and would get documented and the get_configuration_dir could remain but simply be `return filesystem.conf_path` then I concur that would be quite reasonable

What made me think of the change I suggested is the existence of awesome.conffile, awesome.icon_path and awesome.themes_path

And then there's these...
```
function filesystem.get_themes_dir()
function filesystem.get_awesome_icon_dir()
```

**Comment by Sorky** [comment]
I figured that out eventually - I'd even go so far as to suggest they be done like you suggested for the conf_path but of course the up/downside would be that they could be changed 

I can confirm that the awesome. ones are definitely fixed
