### ISSUE TITLE
Notification always executes the action

### ISSUE THREAD

**Issue by ayushjaipuriyar** [awesomeWM/awesome#3944]
```
awesome v4.3-1655-gad0290bc1-dirty (Too long)
 • Compiled against Lua 5.4.7 (running with 0.9.2)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**
- A notification from any app that supports actions, let's say slack.

**Actual result:**

- As soon as the notifications arrives, the app is forced to open even when no actions were taken.

**Expected result:**

- The notification should just time out if no actions are taken.

This wasn't the case earlier, but in the recent commits this started to happen.

**Comment by ayushjaipuriyar** [comment]
> Can you check with `bustle` is the action is indeed taken rather than this being something else? Also, do you use the legacy notification module or the new one (aka, do you have a `naughty.connect_signal("request::display"...` section in your config, which indicates the new one is used)

I am using the new one, as I have that line in my configs.
And yes in bustle, it shows like
- Notifications arrived
- 3 seconds have passed, the time I have set as timeout of notifications
- The notification actions invoked is called
- the notifications action closed is called.

**Comment by numkem** [comment]
I'm on current master and I've noticed that even when you right click on the notification (used to just close it) now it execute the action anyway. Might be related?

**Comment by ayushjaipuriyar** [comment]
> I'm on current master and I've noticed that even when you right click on the notification (used to just close it) now it execute the action anyway. Might be related?

could be 
we might have been able to figure out which may be causing this
[Reddit link](https://www.reddit.com/r/awesomewm/comments/1euiwzo/comment/ljbuw7x/?context=3)
[pull request](https://github.com/awesomeWM/awesome/pull/3863/files)

**Comment by Aire-One** [comment]
I think https://github.com/awesomeWM/awesome/pull/3906 tries to fix this behavior.

**Comment by Elv13** [comment]
I merged the PR, please update and retry

**Comment by ayushjaipuriyar** [comment]
> I merged the PR, please update and retry

Apparently did not fix the issue. Currently, as soon as the timeout of the notification finishes the action is executed.

**Comment by EXtremeExploit** [comment]
Any updates on this? its super annoying not being able to dismiss notifications and forced to reload awesome for them to go away

**Comment by actionless** [comment]
@EXtremeExploit does your awesome version newer than https://github.com/awesomeWM/awesome/pull/3906 ?

**Comment by EXtremeExploit** [comment]
Yes, there is even a comment from ayushjaipuriyar saying that PR didnt fix the issue
Dismissing still executes action
