### ISSUE TITLE
In fullscreen vertical offset

### ISSUE THREAD

**Issue by Genolka** [awesomeWM/awesome#4006]
Output avesome -v
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

System info
```
OS: Arch Linux x86_64
Host: 81Y4 IdeaPad Gaming 3 15IMH05
Kernel: 6.14.2-arch1-1
Packages: 631 (pacman)
Shell: bash 5.2.37
Resolution: 1920x1080, 1680x1050
WM: awesome
CPU: Intel i5-10300H (8) @ 4.500GHz
GPU: Intel CometLake-H GT2 [UHD Graphics]
GPU: NVIDIA GeForce GTX 1650 Ti Mobile
```
I have two monitors, one main from laptop and additional external, so I use xrandr script for them
```
#!/bin/sh
xrandr \
              --output eDP-1 --auto --primary \
              --output HDMI-1-0 --auto --left-of eDP-1
```

## So my problem
I'm a new to linux and I installed new bare arch and on top installed this [dots](https://github.com/Manas140/dotfiles) but this problem I have even before I installed dots, so its caused not by them.
Whenever I open anything in fullscreen, usually right now its videos on youtube, or also in browser with f11 turned on. My screen offsets vertically up.

![Image](https://github.com/user-attachments/assets/2758ec98-17f2-4feb-a4cd-a615f051d458)
So on screenshot you can see that name of the video on top go out of screen and at the bottom under the video is black line (but video is 16:9 as like my main monitor so this line should not exist there) 

The same happend when I use f11 in browser (fullscreen mode for browser)
![Image](https://github.com/user-attachments/assets/5fbad557-4f74-488c-bfa7-7da30a7940bd)
I can't even see my tabs, but they are there.

> Also I have problem with vsync (its not work at all), but I hope I will figure out how to fix it.
> If you need any other info/configs/etc inform me.

**Comment by coralcable** [comment]
I'm experimenting the same issue on a fresh installation of awesome. I haven't touched any configuration file, just `apt install awesome` and then log in a new session.

```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

I've noticed that I can replicate the issue on Firefox but **not** on `Ungoogled Chromium` : here the fullscreen is correctly displayed.

**Comment by Genolka** [comment]
@MinasMazar I found a way how to fix it, but its kinda not for everyone. I just deleted completely "Top titlebar" for client. For me its ok, cause i don't need them.
Also find in couple old issues, that turning off "Hardware acceleration" can help. But right now I have it turned on and without titlebars its work fine.
So i think if you need titlebars, you can add to config rule/signal to turn off titlebar when  firefox (or for all clients) in a fullscreen state.
Like it was made in #1607 by psychon. But me its not helped.

**Comment by Perlovka** [comment]
It happens only in Firefox. All other apps are OK for me.

**Comment by carschandler** [comment]
Same experience here, also an nvidia user. ~seems it could be an nvidia-specific issue if disabling hardware acceleration fixes for some.~

Since this seems to be somewhat related to native title bars; I thought I'd chime in that in i3, I noticed that Firefox does not show the native titlebar window controls (minimize, maximize, close) in tiling mode, but when it goes fullscreen, these do appear. In awesome, they show always by default. No idea if this is helpful, just extra context.

**Comment by parinioa** [comment]
My minimalist fix for this was to add the following to rc.lua

```
client.connect_signal("property::fullscreen", function(c)
    if c.class == 'firefox-esr' then  --Fix shifted fullscreen video in firefox
        local awful = require("awful")
        local beautiful = require("beautiful")
        local tb_height = awful.titlebar(c).height --Custom Titlebar height
            or math.floor(tonumber(beautiful.get_font_height(beautiful.get().font)*1.5)) --Default Titlebar height
            or 45 --Failsafe
        if c.fullscreen then
            c.height = c.height + tb_height
            awful.titlebar.hide(c)
        else
            c.height = c.height - tb_height
            awful.titlebar.show(c)
        end
    end
end)
```

**Comment by disconsented** [comment]
That didn't quite work for me, in my case, the titlebar needs to be disabled for FF to function as expected in fullscreen.

For now, I've just disabled titlebars for FF which isn't ideal but better than before for me:


```lua
-- Add titlebars to normal clients and dialogs
{
    rule_any = {
        type = { "normal", "dialog" }
    },
    except = { class = "firefox" },
    properties = { titlebars_enabled = true }
},
```

I've got a hunch the approach of reacting to full-screen changes is the right one, but, I've not figured out the rest from here. Hiding doesn't seem sufficient, it seems like it needs to be disabled.

**Comment by disconsented** [comment]
Swapping the order of setting the window height & titlebar management solved it for me properly!

```lua
client.connect_signal("property::fullscreen", function(c)
    if c.class == 'firefox' then
        local awful = require("awful")
        local beautiful = require("beautiful")
        local tb_height = awful.titlebar(c).height --Custom Titlebar height
                or math.floor(tonumber(beautiful.get_font_height(beautiful.get().font)*1.5)) --Default Titlebar height
                or 45 --Failsafe
        if c.fullscreen then
            awful.titlebar.hide(c)
            c.height = c.height + tb_height
        else
            awful.titlebar.show(c)
            c.height = c.height - tb_height
        end
    end
end)
```

**Comment by yureitzk** [comment]
Experience the same issue with Firefox, AMD user. 

```sh
$ awesome -v
awesome v4.3-1688-g97e89b1e-dirty (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

This [solution](https://github.com/awesomeWM/awesome/issues/4006#issuecomment-3448913667) fixes the issue (just have to change titlebar size to mine). I also can call `awful.client.floating.toggle` twice when focused on Firefox, and it fixes the offset until the next restart.

I noticed that the issue happens with the default `rc.lua` configuration file too. I tried running a nested X server (`Xephyr`) and saw that fullscreen mode works as it should, on both, on my config and the default one. Maybe it's somehow related to the lack of hardware acceleration in this environment. Running `Xephyr` as standalone gives the same results.

Looks like it's related to the default configuration of titlebars in `rc.lua`. Firefox has a weird behavior when it always wants to have a titlebar (as a window decoration), when most other clients are fine with having it only when necessary/when specified.

<details>
  <summary>Default configuration</summary>

```lua
client.connect_signal("request::titlebars", function(c)
    -- buttons for the titlebar
    local buttons = {
        awful.button({ }, 1, function()
            c:activate { context = "titlebar", action = "mouse_move"  }
        end),
        awful.button({ }, 3, function()
            c:activate { context = "titlebar", action = "mouse_resize"}
        end),
    }

    awful.titlebar(c).widget = {
        { -- Left
            awful.titlebar.widget.iconwidget(c),
            buttons = buttons,
            layout  = wibox.layout.fixed.horizontal
        },
        { -- Middle
            { -- Title
                halign = "center",
                widget = awful.titlebar.widget.titlewidget(c)
            },
            buttons = buttons,
            layout  = wibox.layout.flex.horizontal
        },
        { -- Right
            awful.titlebar.widget.floatingbutton (c),
            awful.titlebar.widget.maximizedbutton(c),
            awful.titlebar.widget.stickybutton   (c),
            awful.titlebar.widget.ontopbutton    (c),
            awful.titlebar.widget.closebutton    (c),
            layout = wibox.layout.fixed.horizontal()
        },
        layout = wibox.layout.align.horizontal
    }
end)
```

</details>

My idea is to hide titlebar when clients enter fullscreen mode, and restore it if the client had a titlebar before. I've been using this solution for a while now and it's worked fine so far. But I'd like to know if there's a better solution for this :)

<details>
  <summary>My configuration</summary>

```lua
local titlebar_size = dpi(18)

-- Add a titlebar if titlebars_enabled is set to true in the rules.
client.connect_signal("request::titlebars", function(c)
    -- buttons for the titlebar
    local buttons = gears.table.join(
        awful.button({ }, 1, function()
            c:emit_signal("request::activate", "titlebar", {raise = true})
            awful.mouse.client.move(c)
        end),
        awful.button({ }, 3, function()
            c:emit_signal("request::activate", "titlebar", {raise = true})
            awful.mouse.client.resize(c)
        end)
    )

	local titlebar  = awful.titlebar(c, {
		size    = titlebar_size
	})

    titlebar : setup {
        { -- Left
            awful.titlebar.widget.iconwidget(c),
            buttons = buttons,
            layout  = wibox.layout.fixed.horizontal
        },
        { -- Middle
            { -- Title
                align  = "center",
                widget = awful.titlebar.widget.titlewidget(c)
            },
            buttons = buttons,
            layout  = wibox.layout.flex.horizontal
        },
        { -- Right
            awful.titlebar.widget.floatingbutton (c),
            awful.titlebar.widget.maximizedbutton(c),
            awful.titlebar.widget.stickybutton   (c),
            awful.titlebar.widget.ontopbutton    (c),
            awful.titlebar.widget.closebutton    (c),
            layout = wibox.layout.fixed.horizontal()
        },
        layout = wibox.layout.align.horizontal
    }
end)

local function setTitlebar(client, s)
    if (s) then
        if client.titlebar == nil  then
            client:emit_signal("request::titlebars", "rules", {})
        end

        if not (client.titlebars_enabled) then
			awful.titlebar.show(client)
			client.titlebar_present = true
        end
    else
        awful.titlebar.hide(client)
        client.titlebar_present = false
    end
end

client.connect_signal("property::fullscreen", function(c)
    if c.fullscreen then
        awful.titlebar.hide(c)

		gears.timer.delayed_call(function()
			if c.valid then
				c:geometry(c.screen.geometry)
			end
		end)
    else
        if c.titlebar_present then
            setTitlebar(c, c.titlebar_present)
            c.height = c.height - titlebar_size
        end
    end
end)
```
</details>

I also manually added code from [this PR](https://github.com/awesomeWM/awesome/pull/4023) into my awesome configuration to fix [an issue with Firefox's tiling](https://superuser.com/questions/1206957/cannot-get-firefox-to-tile-correctly-after-last-update-to-awesome-wm-in-arch). Previously, I used the rule from the linked post, but seems like this PR makes it obsolete.

**Comment by actionless** [comment]
did this got fixed by https://github.com/awesomeWM/awesome/pull/4023 ?

**Comment by faretek1** [comment]
I still have this issue (with zen browser and with firefox, but not with chromium). on nvidia on nixos

here's the hook to `property::fullscreen` that i made:

```lua
client.connect_signal("property::fullscreen", function(c)
    if c.fullscreen then
        awful.titlebar.hide(c)
        c:geometry(c.screen.geometry)
    else
        awful.rules.apply(c)
    end
end)
```

it will add the titlebar back if the rules think that there should be a titlebar. so if your rules say that a window should not have a titlebar, it will not suddenly give birth to a titlebar when it exits fullscreen mode

###### my dotfiles are on codeberg

**Comment by actionless** [comment]
@faretek1 but does the problem reproducible with the default rc.lua config?

**Comment by faretek1** [comment]
> [@faretek1](https://github.com/faretek1) but does the problem reproducible with the default rc.lua config?

i briefly replaced my `rc.lua` with the default one and reloaded the config however the issue still occurs. however i did not restart the computer

**Comment by atpage** [comment]
I'm still working around the issue with `titlebars_enabled = false` for Firefox.  But that's on awesome 4.3, not master.
